name: Code checks
on:
  - push
  - pull_request

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      ALLOWED_HOSTS: "*"
      SECRET_KEY: "my big secret not seen"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js globally
        run: |
          sudo npm install -g n
          sudo n 20
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs/req_linux.txt -r reqs/dev.txt

      - name: Test it
        run: pytest
